global using Modding;
global using MonoMod.RuntimeDetour;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Diagnostics;
global using UnityEngine;
global using UnityEngine.SceneManagement;
global using UObject = UnityEngine.Object;
global using UCamera = UnityEngine.Camera;
global using USceneManager = UnityEngine.SceneManagement.SceneManager;
global using Logger = Modding.Logger;
