name: Build and Publish

on: workflow_dispatch

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Unity Engine modules
        run: |
          wget https://files.catbox.moe/i4sdl6.zip -O UnityModules.zip
          unzip UnityModules.zip -d References

      - name: Fetch API files
        run: |
          wget https://github.com/hk-modding/api/releases/latest/download/ModdingApiWin.zip -O API.zip
          unzip -o API.zip -d References

      - name: Setup MSBuild
        run: sudo apt-get install -y nuget mono-devel mono-xbuild

      - name: Build project
        run: dotnet build --configuration Release

      - name: Get SHA256 of zipped mod
        id: get_hash
        run: echo "hash=$(sha256sum Output/OneLevel.zip | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

      - name: Get Assembly version
        id: get_version
        run: echo "version=$(cat < Version.txt)" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          target_commitish: ${{ github.sha }}
          tag_name: "${{ steps.get_version.outputs.version }}"
          name: "v${{ steps.get_version.outputs.version }}"
          body: "SHA256: ${{ steps.get_hash.outputs.hash }}"
          files: ./Output/*.dll
